version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules
    # run tests!
    #- run: yarn test
  package:
    working_directory: ~/project
    docker:
      - image: circleci/node:9-browsers
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Setup Environment Variable
          command: |
            echo "export PATH=$PATH:~/project/node_modules/.bin" >> $BASH_ENV
      - attach_workspace:
          at:  ~/project
      - run:
          name: package
          command:
            npm i
            npm run package
      - run:
         name: release
         command: npm run semantic-release || true
workflows:
  version: 2
  build:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
  package:
    jobs:
      - hold:
          type: approval
          requires:
            - build
      - package:
          requires:
            - hold
